# Traefik configuration file
# This file configures the reverse proxy for the Actual Budget setup

# Global configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# API and dashboard configuration
api:
  dashboard: true
  insecure: true  # Only for local development, use secure in production

# Entry points configuration
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

# Providers configuration
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: actual-network
  file:
    directory: /etc/traefik/dynamic
    watch: true

# Logging configuration
log:
  level: INFO
  format: json

# Access logs
accessLog:
  format: json
  fields:
    defaultMode: keep
    headers:
      defaultMode: keep

# Metrics configuration (optional)
metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

# Certificate resolvers
certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@example.com
      storage: /data/acme.json
      httpChallenge:
        entryPoint: web 